# Generated by Django 4.1.7 on 2023-03-20 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=500)),
                ('Email', models.EmailField(default='', max_length=600)),
                ('Query', models.TextField()),
                ('Phone', models.PositiveIntegerField()),
                ('Date', models.DateField(default=datetime.datetime(2023, 3, 20, 12, 56, 29, 387116))),
            ],
        ),
    ]
