# Generated by Django 4.1.7 on 2023-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='Date',
            field=models.DateField(default=''),
        ),
    ]
