# Generated by Django 4.1.7 on 2023-03-25 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_contactrequest_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactrequest",
            name="Phone",
        ),
    ]
