# Generated by Django 4.1.7 on 2023-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AyurvedaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(default="", max_length=500)),
                ("Detail", models.TextField(default="", max_length=6000)),
                ("Photo", models.ImageField(upload_to="")),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
