# Generated by Django 4.1.7 on 2023-03-24 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_ayurvedamodel_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AyurvedaModel",
        ),
    ]
