# Generated by Django 4.1.7 on 2023-03-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayurvedamodel",
            name="Photo",
            field=models.ImageField(upload_to="vedamedia/", verbose_name="Photo"),
        ),
    ]
