# Generated by Django 4.1.7 on 2023-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_ayurvedamodel_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayurvedamodel",
            name="Photo",
            field=models.ImageField(upload_to="", verbose_name="Photo"),
        ),
    ]
